### ISSUE TITLE
Input - Clear input field

### ISSUE THREAD

**Issue by WebDevMR** [DevvitIO/Multiplayer-Hangman#11]
Have the input field clear once the user enters a letter guess.

**Comment by charly3pins** [comment]
I would like to take this

**Comment by WebDevMR** [comment]
@charly3pins Awesome! Before you begin though could you join the organization and come say hi in our discord channel first? All the info is in the README of this project.

**Comment by charly3pins** [comment]
Oh sure @WebDevMR !

**Comment by charly3pins** [comment]
@WebDevMR I see this issue is fixed in this merge https://github.com/charly3pins/Multiplayer-Hangman/commit/c9ec86165b02427d69a2b333b7b1311f0ac8bffd#diff-7f9d7745f16bb572e41cb88f8eaf7734R77

**Comment by WebDevMR** [comment]
Somebody must've gotten to it without commenting first.

**Comment by WebDevMR** [comment]
@charly3pins were you doing this for hacktoberfest? There' still an issue to add a google font to the site, that one should only take  few mins. I'm closing this issue for now.
