### ISSUE TITLE
UX Issue, Enter key not working on input button.

### ISSUE THREAD

**Issue by nawazishali** [DevvitIO/Multiplayer-Hangman#13]
I think It would be a better UX if user would be able to submit the input using keyboard. And typing and clicking on submit button can quickly frustrate the player.

I would love to take this issue and make a PR. If you are OK with it?

**Comment by WebDevMR** [comment]
@nawazishali Would be awesome if you could work on it for sure, but could you join the organization and come say hi in our discord channel first? All the info is in the README of this project.

**Comment by nawazishali** [comment]
Feature implemented. This Issue is closed now.
