### ISSUE TITLE
Display each body part as user selects incorrectly.

### ISSUE THREAD

**Issue by WebDevMR** [DevvitIO/Multiplayer-Hangman#2]
Use the images in src/assets/img to get you started

**Comment by abderra7** [comment]
I like this project, if you want I can resolve this also

**Comment by WebDevMR** [comment]
@abderra7 Sure thing man! The images are kinda rough, so just be aware of that. They're super place holder for right now. Feel free to just nudge them into place to create the hangman for the time being.
