### ISSUE TITLE
Solve socket build errors

### ISSUE THREAD

**Issue by TheGrimJam** [DevvitIO/Multiplayer-Hangman#33]
"""
The solution that works without changing the build process is requireing the socket.io-client in clientSocket.js

    var io = require("socket.io-client");
    var socket = io('http://localhost:5000');

That tells webpack that it should add it to the bundle
In that case you don't need the socket.js file at all and you don't need to load it separately in the index.html file
I guess I could change the babel config so everything is put back on global. let me know what you think is the way to go
"""

ken

**Comment by KenavR** [comment]
I wrote a longer post about this in the PR #32
