### ISSUE TITLE
Find a nice font to use and implement on site

### ISSUE THREAD

**Issue by SpaceOso** [DevvitIO/Multiplayer-Hangman#4]
Use something besides Times New Roman...I'm on windows this is the default font I see.

Use google fonts.

**Comment by Dission** [comment]
font-family: "Century Gothic", CenturyGothic, AppleGothic, sans-serif;

**Comment by SpaceOso** [comment]
@Dission want to open a PR for it? Read over the README to join our discord channel and the organisation.

**Comment by Dission** [comment]
Sure.
