### ISSUE TITLE
Parse .txt file to get a new random word

### ISSUE THREAD

**Issue by SpaceOso** [DevvitIO/Multiplayer-Hangman#5]
This file is now in the src folder.

Find a way to read it's contents.

Pass a word with 5 or more characters to store and set it as the secretWord

**Comment by jnelson180** [comment]
I can get this one.

**Comment by WebDevMR** [comment]
nice! All yours @jnelson180

**Comment by jnelson180** [comment]
Awesome. About to send my PR.

**Comment by jnelson180** [comment]
https://github.com/DevvitIO/Multiplayer-Hangman/pull/22
